services:
  web:
    build: .
    ports:
      - "60001:80"
  mysql:
   image: mysql:5.7.17
   container_name: mysqltest
   volumes:
      - "./src/sqldir:/home"
   environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=jkba
   ports:
    - "60002:3306"
